package by.murashko.sergey.entities;
// Generated Jul 1, 2016 9:05:26 AM by Hibernate Tools 4.3.1.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;
import javax.validation.constraints.Size;
import javax.xml.bind.annotation.XmlRootElement;

import org.hibernate.annotations.Fetch;
import org.hibernate.annotations.FetchMode;
/**
 * Users generated by hbm2java
 */
@Entity
@Table(name = "users", catalog = "springlib", uniqueConstraints = @UniqueConstraint(columnNames = "name"))
public class Usersdss implements java.io.Serializable {

	private Long id;
	@Size(min = 4, message = "{name.size.error}")
	private String name;
	@Size(min = 4, max = 10, message = "{password.size.error}")
	private String password;
	@Size(min = 5, max = 20, message = "{mail.size.error}")
	private String mail;
	private Integer isAdmin;
	private Set<Messages> messageses = new HashSet<Messages>(0);
	public Usersdss() {
	}

	public Usersdss(String name, String password, String mail) {
		this.name = name;
		this.password = password;
		this.mail = mail;
	}

	public Usersdss(String name, String password, String mail, Integer isAdmin) {
		this.name = name;
		this.password = password;
		this.mail = mail;
		this.isAdmin = isAdmin;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}
	public void delId(){
		this.id = null;
	}

	@Column(name = "name", unique = true, nullable = false, length = 15)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "password", nullable = false, length = 15)
	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	@Column(name = "mail", nullable = false, length = 40)
	public String getMail() {
		return this.mail;
	}

	public void setMail(String mail) {
		this.mail = mail;
	}

	@Column(name = "is_admin")
	public Integer getIsAdmin() {
		return this.isAdmin;
	}

	public void setIsAdmin(Integer isAdmin) {
		this.isAdmin = isAdmin;
	}
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "messages")
	
	public Set<Messages> getMessageses() {
		return this.messageses;
	}

	public void setMessageses(Set<Messages> messageses) {
		this.messageses = messageses;
	}

}
